apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dev
  name: fastapi-config
data:
  APP_NAME: "My FastAPI App"
  ENV: "production"
  MY_COLOR: "blue"
  MY_CITY: "Kyiv"
  MY_MESSAGE: "Hello from ConfigMap"